iemocap:
  DGI_lambda: 0.1
  NACL_lambda: 0.5
  T: 5
  VATT_lambda: 0.3
  act_dropout: 0.0
  activation_fn: gelu
  apply_graphormer_init: false
  at_NCE_lambda: 1
  attention_dropout: 0.0
  av_NCE_lambda: 1
  batch_size: 12
  centrality: degree
  data_dir_path: data
  device: cuda:2
  do_CE: true
  do_DGI: false
  do_MAE: false
  do_NACL: false
  do_VATT: false
  do_WCE: false
  dropout: 0.3
  edge_type: multi_hop
  emotion: 6class
  encoder_attention_heads: 6
  encoder_embed_dim: 384
  encoder_layers: 2
  encoder_normalize_before: true
  epochs: 200
  experiment_in_comet: false
  ffn_embed_scaler: 4
  from_scratch: false
  learning_rate: 0.0001
  log_in_comet: false
  max_dist: 51
  max_grad_value: -1
  max_nodes: 500
  modalities: atv
  multi_hop_max_dist: 51
  n_finetune_dialogues: 36
  n_finetune_utterances: 1751
  n_pretrain_dialogues: 108
  n_pretrain_utterances: 3200
  n_test_dialogues: 31
  n_test_utterances: 943
  n_valid_dialogues: 12
  n_valid_utterances: 400
  no_token_positional_embeddings: false
  num_classes: 6
  num_edge_dis: 51
  pre_layernorm: true
  save_analysis_path: save/analysis/iemocap
  save_model_checkpoint: model_checkpoints/iemocap
  scheduler: cosineLR_linearWarmUp
  seed: 20242025
  share_encoder_input_output_embed: false
  sub_classifier_dim: 128
  temperature: 0.05
  topk: 5
  tv_NCE_lambda: 1
  unimodal_inference: false
  unimodal_lambda: 0.1
  weight_decay: 1.0e-05
