meld:

  seed: 69
  device: "cuda:2"
  data_dir_path: "data"
  save_model_checkpoint: "model_checkpoints/meld"
  save_analysis_path: "save/analysis/meld"
  log_in_comet: False
  experiment_in_comet: False
  n_train_dialogues: 1432
  n_train_utterances: 13708
  n_valid_dialogues: 144
  n_valid_utterances:
  n_test_dialogues: 280
  n_test_utterances:
  modalities: "atv"

  hybrid: false
  specific: false

  from_begin: false

  epochs: 300
  batch_size: 128
  scheduler: "cosineLR_linearWarmUp" # <- [stepLR,multistepLR, reduceLR, cyclicLR, cosineLR]
  T: 5 # duration of scheduler
  learning_rate: 0.0003
  weight_decay: 0.03

  encoder_layers: 2 # [2, 3, 4] test
  encoder_attention_heads: 6 # [4, 6, 8] test , i.e., each head's dim [96, 64, 48]
  encoder_embed_dim: 384 # [256, 384, 512] test
  ffn_embed_scaler: 4 # encoder_embed_dim * 4
  sub_classifier_dim: 128
  num_classes: 7

  do_NACL: false
  do_MAE: false
  do_VATT: true
  do_CE: False
  do_WCE : False

  mask_prob_a: 0.5
  mask_prob_t: 0.5
  mask_prob_v: 0.5

  topk: 7
  NACL_lambda: 1
  MAE_lambda: 1

  temperature: 0.1
  max_grad_value: -1
  dropout: 0.1
  attention_dropout: 0.
  emotion: "meld_7"
  centrality: "degree"
  act_dropout: 0.0
  max_nodes: 500
  max_dist: 51
  num_edge_dis: 51
  multi_hop_max_dist: 51

  do_MIM: False

  edge_type: multi_hop # single_hop, multi_hop
  share_encoder_input_output_embed: False # share encoder input and output embeddings"
  no_token_positional_embeddings: False # if set, disables positional embeddings" " (outside self attention)
  apply_graphormer_init: False # use custom param initialization for Graphormer
  activation_fn: "gelu"  # activation function to use
  encoder_normalize_before: True  # apply layernorm before each encoder block
  pre_layernorm: True
